version: 2.1

commands:
  restore_module_cache:
    parameters:
      module_path:
        type: string
    steps:
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-<< parameters.module_path >>-{{ checksum "<< parameters.module_path >>/yarn.lock" }}
  save_module_cache:
    parameters:
      module_path:
        type: string
    steps:
      - save_cache:
          key: v{{ .Environment.CIRCLECI_CACHE_VERSION }}-dependencies-<< parameters.module_path >>-{{ checksum "<< parameters.module_path >>/yarn.lock" }}
          paths:
            - << parameters.module_path >>/node_modules
  lint:
    steps:
      - run:
          name: "Lint Files"
          command: yarn lint
  install:
    steps:
      - run:
          name: "Install dependencies"
          command: yarn
  type-check:
    steps:
      - run:
          name: "Verify types"
          command: yarn type-check

  setup_and_test:
    steps:
      - checkout
      - restore_module_cache: { module_path: ./ }
      - install
      - type-check
      - lint
      - save_module_cache: { module_path: ./ }

  run_deploy_script:
    steps:
      - checkout
      - restore_module_cache: { module_path: ./ }
      - run: yarn
      - save_module_cache: { module_path: ./ }

jobs:
  test:
    docker:
      - image: circleci/node:dubnium-browsers
    working_directory: ~/app
    steps:
      - setup_and_test

workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - test
